AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Resources:
  SmfLambdaFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Runtime: java8
      Handler: com.jdm.aws.smf.event.S3EventHandlerUpdateIndex::handleSearch
      #      Handler: com.jdm.aws.smf.SmfInstrumentSearchLambda::handleSearch
      #      Handler: com.jdm.aws.smf.SmfInstrumentSearchAWS4SSignerLambda::handleSearch
      #      Handler: com.jdm.aws.smf.SmfInstrumentSearchPojoLambda::handleSearch
      Timeout: 60
      CodeUri: ./target/lambda.jar
